app = 'infinite-story'
primary_region = 'hkg'

[build]

[env]
  NODE_ENV = 'production'
  NEXT_TELEMETRY_DISABLED = '1'
  DATABASE_URL = 'file:/app/prisma/prod.db'

[mounts]
  source = 'infinite_story_data'
  destination = '/app/prisma'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
